:ERROR 2024-11-10 10:03:48,789 - Exception
Traceback (most recent call last):
  File "C:\Users\ps21\PycharmProjects\firstRepo2\10-11\L3_33.py", line 17, in <module>
    print(10/0)
ZeroDivisionError: division by zero
